### ISSUE TITLE
Recipe Book Malfunctions with Some Recipes

### ISSUE THREAD

**Issue by bconlon1** [The-Aether-Team/The-Aether-II#114]
> Shift-clicking the recipe book to make blue or purple parachutes with those parachutes already in your inventory causes the colored parachute to be moved into the recipe book, causing an invalid crafting. This also occurs with bolts, but somewhat different. When you have all the required materials for bolts in your inventory and you shift-click the recipe book to move them in, it moves only the shards and the sticks; never the feathers, regardless of what feather type you have. Both could be the cause of the recipes not reading the data of the item required in the recipe.

**Comment by M4RVlN** [comment]
Shift-clicking does not work on items with NBT. https://bugs.mojang.com/browse/MC-129057
